addres = input("Enter home addres: ")
work = input("Enter your place of work: ")
school = input("Enter your school name: ")
hobby = input("Enter your hobby: ")
food = input("Enter your favourite food: ")
print("---------------**Result's:**---------------")
print("Okay, Your results are ready!")
print("Your Home addres is " + addres)
print("Your Place of work is " + work)
print("Your School name is " + school + "(very nice)")
print("Your Hobby is " + addres)
print("Your Favourite Food is " + work)
print("Thanks for Rigistration!")